### ISSUE TITLE
Error when loading ppt/pptx documents

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#1]
This issue was originally raised via forum topic:
[https://forum.groupdocs.com/t/preview-for-large-files-takes-long-time/5889/21](https://forum.groupdocs.com/t/preview-for-large-files-takes-long-time/5889/21)

A user reported that he is getting error _"The path is not of a legal form."_ when loading documents. After the investigation, it is found that the issue is specific for ppt/pptx documents. 
Error screenshot: https://imgur.com/uGvrWAd.

Regards

**Comment by Pavel-Teplitsky** [comment]
Hi @usmanazizgroupdocs ,

Following issue has been fixed in b1f53bb35e459949c645a5eded1bd095c11e2202 commit:
* "The path is not of a legal form."  for ppt/pptx files
