### ISSUE TITLE
Print Preview has excessive blank pages.

### ISSUE THREAD

**Issue by BorisPazinAspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#11]
When try to print DOCX document ([Calibre.docx](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App/blob/master/WebForm-Modern-UI/App_Data/calibre.docx)), original document has 3 pages. 

When click Print button, then the print preview shows 6 pages. 3 new empty pages are added in print preview. 

But, after document is printed, output document has correctly only 3 pages.

**Comment by bobkovalex** [comment]
@BorisPazinAspose 

Please provide more detailed error log:

- Viewer mode - html or image?
- Browser and browser version (or this issue can be reproduced in all modern browsers)?

**Note**: for further reports please always provide as much information as possible.

Thanks.

**Comment by BorisPazinAspose** [comment]
@bobkovalex 

Viewer mode is HTML. When using Image mode everything works correctly.

Here are more details about web browser behavior on my side:

Google Chrome 70.0.3538.77 (64-bit) - Print preview has 6 pages instead of 3. There are 3 excessive blank pages. When document is printed, then it is printed correctly and has 3 pages.
FireFox 62.0.3 (64-bit) - Cannot scroll and see preview because of popup window, but printed document has one excessive blank page at the end (4 pages total)
Microsoft Edge 42.17134.1.0 - both Print Preview and printing work correctly.

Please let me know if you need any further assistance with this.

Thanks.

**Comment by Pavel-Teplitsky** [comment]
@BorisPazinAspose We have fixed the issue. Please clean and rebuild the solution (it will pull latest updates for the front-end resources) and make sure that after the build you have "Resources\viewer\js\viewer.js"1.3.0 version and you have cleaned browsers cache.

**Comment by Pavel-Teplitsky** [comment]
@BorisPazinAspose We have fixed the issue for FireFox on Windows 10. To get latest version of the front-end please follow steps described in my previous comment (please make sure you have the viewer.js 1.5.0 version).

**Comment by BorisPazinAspose** [comment]
@Pavel-Teplitsky 

I confirm the issue is fixed. Thanks.
