### ISSUE TITLE
The document is corrupted after applying a watermark

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#18]
Hi,
Please notice the document content is misplaced after applying a watermark.
The watermark is inserted using the following code snippet,
```
    HtmlOptions htmlOptions = new HtmlOptions();
    htmlOptions.PageNumber = pageNumber;
    htmlOptions.CountPagesToRender = 1;
    htmlOptions.EmbedResources = true;

    htmlOptions.Watermark = new Watermark("This is a watermark: " + DateTime.Now);
    htmlOptions.Watermark.Color = Color.Red;
```
The screenshot of the issue can be found here:
https://drive.google.com/open?id=1xvtOX0nOriw8U1vldHopXC9L2hV9uase
Thanks.

**Comment by Pavel-Teplitsky** [comment]
@aleksandarvidakovicaspose we have fixed the issue. Please clean and rebuild the solution. Updated front-end resources will be installed automatically. Also please do not forget to clean the browser cache.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @Pavel-Teplitsky,
Thanks for the prompt response. It works great now.
Best Regards.
