### ISSUE TITLE
The Viewer doesn't respond until the entire document is loaded

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#19]
Hi,
Please notice that the Viewer freezes while loading a huge document.
During the document loading, it isn't possible to zoom, unzoom, or scroll until the loading finishes.
Thanks.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose for huge documents we have an option `preloadPageCount` in `configuration.yml` that allows you to specify the number of pages to be loaded when the document is opened and will lazy-load remaining pages while you scroll a document. 

Let us know if this works in your case.

**Comment by Pavel-Teplitsky** [comment]
Hi @aleksandarvidakovicaspose we have fixed the issue. Please clean and rebuild the solution. Updated front-end resources will be installed automatically. Also please do not forget to clean the browser cache.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @Pavel-Teplitsky 
I have tested the Viewer application and it's working fine now.
Thanks a lot.
