### ISSUE TITLE
Restriction of right click to avoid downloading of images

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#2]
This feature was requested via the forum topic: [https://forum.groupdocs.com/t/right-click/6600](https://forum.groupdocs.com/t/right-click/6600)

One of the users requested the feature of restricting the right click to avoid the downloading of images in image-based rendering.

**Comment by egorovpavel** [comment]
@usmanazizgroupdocs although this request is quite old, we are going to schedule implementation of this feature in the next two weeks.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Thanks for the updates.

**Comment by Pavel-Teplitsky** [comment]
@usmanazizgroupdocs Sorry for the delay. We have released this feature. Please download latest version of the example from this repository and use "enableRightClick" property in the configuration.yml to enable/disable right mouse click.

Best regards.

**Comment by usmanazizgroupdocs** [comment]
@Pavel-Teplitsky Thanks.
