### ISSUE TITLE
Adding the watermark configuration feature 

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#22]
Hi,

Please consider the implementation of the watermark configuration feature using the configuration file. At the moment, it's possible to set the watermark at the compile time. However, this approach doesn't suit the customer's need.
This issue looks very similar to the previously logged one,
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/issues/3

Thanks.

**Comment by Pavel-Teplitsky** [comment]
Hi, we added this to our road map for future implementation. Meanwhile you can add this feature by yourself following these [instructions](https://docs.groupdocs.com/display/viewernet/Apply+Watermark+on+the+HTML+Representation+of+the+Documents) or if you use image representation mode use these [instractions](https://docs.groupdocs.com/display/viewernet/Apply+Watermark+on+the+Image+Representation+of+the+Documents).

**Comment by Pavel-Teplitsky** [comment]
Hi, I can confirm that the watermark will be in the printed document but not in the document itself (if to download it - it will be without watermark). If you need to save watermark into the document please take a look at [GroupDocs.Watermark](https://products.groupdocs.com/watermark) . Example for this library is not available currently but we have it in our road map, please stay tuned and we will notify you when such example will be ready.

**Comment by Pavel-Teplitsky** [comment]
@aleksandarvidakovicaspose We have released this feature. Please download latest version of the example from this repository and use "watermarkText" property in the configuration.yml to set watermark text.

Best regards.
