### ISSUE TITLE
The scroll bar is covered by the navigation bar 

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#27]
Hi team,

Please notice that the scroll bar is covered by the navigation bar. If a document has more than 30 pages, the scroll bar will be hidden.
Please check the link to the screenshot below,
https://www.photobox.co.uk/my/photo/full?photo_id=501577800912

Thanks.

**Comment by bobkovalex** [comment]
@aleksandarvidakovicaspose 

Hi Aleksandar,
I'm not able to view your screenshot, the link redirects to photobox home page.
Could you please share your screenshot through any other service?
Thanks.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @bobkovalex,
Sure, please find the screenshot attached.
Sorry for the inconvenience.
![scroll bar](https://user-images.githubusercontent.com/41449852/51104929-d6caa600-17e7-11e9-9db2-1591d7118c97.png)

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose the issue has been confirmed. We are working on the fix.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose this issue has been fixed in the latest version.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @egorovpavel 
I have pulled the latest changes. Confirming that the issue is fixed.
Thanks.
