### ISSUE TITLE
The page rotation retains when the document is reloaded  

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#28]
Hi,

The customer is concerned since the rotated page keep this setting when the document is reloaded.
Is this expected behavior, or we can consider this as a bug, please clarify.

Thanks.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose yes, this is expected behavior. However, we are going introduce additional configuration parameter to control this behavior.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose we released the new version where it is possible to control above mentioned behavior with [`saveRotateState`](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/blob/3f65aca58ab1aa2309f144bcf05de441f28d143a/src/configuration.yml#L82) configuration option. Let us know if this solution works for you.
