### ISSUE TITLE
Setting watermark using configuration parameter

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#3]
This feature was requested via the forum topic: [https://forum.groupdocs.com/t/watermark-is-not-working/6605](https://forum.groupdocs.com/t/watermark-is-not-working/6605)

One of the users requested for the feature of setting watermark using the configuration parameter.

**Comment by Pavel-Teplitsky** [comment]
Hi, We we added this to our road map for future implementation. Meanwhile you can add this feature by yourself following these [instructions]("https://docs.groupdocs.com/display/viewernet/Apply+Watermark+on+the+HTML+Representation+of+the+Documents") or if you use image representation mode use these [instractions]("https://docs.groupdocs.com/display/viewernet/Apply+Watermark+on+the+Image+Representation+of+the+Documents").

**Comment by Pavel-Teplitsky** [comment]
@usmanazizgroupdocs Sorry for the delay. We have released this feature. Please download latest version of the example from this repository and use "watermarkText" property in the configuration.yml to set watermark text.

Best regards.

**Comment by usmanazizgroupdocs** [comment]
@Pavel-Teplitsky  Thanks.
