### ISSUE TITLE
The pagination lost synchronization when scrolling the document

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#30]
Hi,

Please notice that pagination isn't synchronized when we the scroll through the document. In both scroll scenarios, using arrows or mouse drag/drop, the page counter is increment/decrement only once regardless how much pages are altered. Finally, the page counter isn't updated to the new position when the scrolling is over.
If more information is needed, please let me know.

Best Regards.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose we weren't able to reproduce the described issue, please provide additional information: browser, configuration.yml or record short screencast.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @egorovpavel,
I have tested the issue using Chrome: Version 71.0.3578.98 (Official Build) (64-bit). Additional information: Windows 7 SP1 and VS 2015.
The requested files, configuration.yml and the short screencast record, are attached. Please let me know if more information is needed.
[video.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/files/2760087/video.zip)
[configuration.yml.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/files/2760099/configuration.yml.zip)

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose thanks for quick response, we identified the issue and working on the fix. We will let you know once we release the new version.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose this issue has been fixed. Please pull the latest changes for this repo and rebuild the solution.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @egorovpavel 
The app has been tested and I'm confirming that the issue has been fixed.
Thanks for a quick resolution.
