### ISSUE TITLE
Forbid the printing if PDF document has this restriction 

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#37]
Hi,

Please notice it is possible to print the document which has the restriction for the printing.
The sample document is attached.
Please advise.
[test secured.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/files/2862890/test.secured.pdf)

Best Regards.

**Comment by Pavel-Teplitsky** [comment]
@aleksandarvidakovicaspose Thank you for your request. Unfortunatly current GroupDocs.Viewer product doesn't support such feature (detect if document has print restrictions). We have addded implimintation of such feature to our roudmap. When this feature will be available We will notify you.

**Comment by Pavel-Teplitsky** [comment]
Hi @aleksandarvidakovicaspose We added supporting for print restrictions. Please download latest version from this repository. If you will have any questions regarding this feature please feel free to contct us.

Best regards.
