### ISSUE TITLE
An exception raises while processing a large PDF document

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#39]
Hi,

Please notice that OOM exception raises while working on the big PDF (~100MB).
The source document can be download using the link below,
https://drive.google.com/open?id=10e44Ka-VgHPACek9wIvbjDvjgaVcYfBo
The file is password protected due to the data privacy and the password will be shared with the assigned developer.
Please find the screenshot of the exception in the attachment.
![exception](https://user-images.githubusercontent.com/41449852/52889732-91e8b500-3181-11e9-8e49-9ff61a5d974d.png)
 
Best Regards.

**Comment by Pavel-Teplitsky** [comment]
@aleksandarvidakovicaspose Please share the password. 
Thank you

**Comment by Pavel-Teplitsky** [comment]
Hi @aleksandarvidakovicaspose Thank you for password sharing. I have checked the issue - used your project and configuration.yml (which you shared in pptx issue thread) and document rendered well with out any issues. Could you please share your PC hardware info.

Best regards.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @Pavel-Teplitsky,
FYI, it seems this issue is related to the IIS configuration, and not to GroupDocs.Viewer library, nor this SDK.
I've used a workaround from the issue https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/issues/38
and it is working fine now.
Thanks for your assistance very much.

**Comment by Pavel-Teplitsky** [comment]
@aleksandarvidakovicaspose Thank you for this information. Can I close this issue?
