### ISSUE TITLE
Regarding Friendly URLs

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#4]
This question was originally raised via forum topic: [https://forum.groupdocs.com/t/preview-for-large-files-takes-long-time/5889/26](https://forum.groupdocs.com/t/preview-for-large-files-takes-long-time/5889/26)

> In the ASP.NET WebForms sample application, WEB API is used with Route/friendly URLs.
> However We don’t have any mechanism for Friendly URLs in current project and it is huge project so we can not include related libraries for WebAPI and FriendlyUrls.
> 
> Any alternative solution to avoid this?

**Comment by bobkovalex** [comment]
@usmanazizgroupdocs 

This can be achieved through a custom implementation of InputDataHander.
Please check following link for more information: https://docs.groupdocs.com/display/viewernet/Working+With+Custom+Input+Data+Handlers
