### ISSUE TITLE
The navigation bar gets corrupted while resizing the browser window

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#41]
Hi,

Please notice that the icons become bigger and leave the navigation bar when the browser window gets smaller. The screenshot which describes the issue is attached.

An ideal approach would be that the icons remain the same size and arranged in two lines inside the navigation bar.

Best Regards.
![navigation issue](https://user-images.githubusercontent.com/41449852/53922761-f78bdb00-4075-11e9-961e-4f042bef84ae.png)

**Comment by Pavel-Teplitsky** [comment]
@aleksandarvidakovicaspose Thank you for your request. We will check and fix it.

Best regards.

**Comment by Pavel-Teplitsky** [comment]
@aleksandarvidakovicaspose Please update your project with the latest commit and don't forget to clean/rebuild your solution. Also please clean your browser cache.

Best regards.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @Pavel-Teplitsky,
Thanks for the expedite. The nav bar looks great, so please feel free to close the issue. 
Best Regards.
