### ISSUE TITLE
The printing doesn't work correctly with the large documents

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#43]
Hi, 

Please notice that the printing doesn't work fine when processing a large document.
For instance, the source PDF document is properly rendered to HTML output in temp folder _./src/DocumentSamples/Viewer/temp/file name/.._, but the printed output contains the empty pages with the message: _Loading... Please wait_.
[Untitled Document.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/files/2964070/Untitled.Document.pdf)

Since the source document contains sensitive data, it has been zipped with the password.
https://drive.google.com/open?id=16SyGnhdGgZPsAZYjRBnh0fOF4oyA9BSF
Please ask for the password by sending an email. 

Best Regards.

**Comment by Pavel-Teplitsky** [comment]
Hi @aleksandarvidakovicaspose thank you for your request. Please send me a password and your configuration.yml file.

Best regards.

**Comment by Pavel-Teplitsky** [comment]
Hi @aleksandarvidakovicaspose Thank you for your email with password and configuration.yml.  We investigating this issue which is related to the document loading performance of the GroupDocs.Viewer product. We will notify you when fix will be available.

Best regards.

**Comment by Pavel-Teplitsky** [comment]
Hi @aleksandarvidakovicaspose Thank you for your patience and sorry for delay. Currently we continue our work on fixing this issue but to save your time we released a temporary workaround. Please update your project with the latest version of the example from this repository.

Best regards.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose Sory for the delay. We have released a workaround for this issue. It will load PDF file directly without processing it for print. Let us know if this workaround works for you.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose did you tried our workaround? Let us know if we can close this issue?

**Comment by aleksandarvidakovicaspose** [comment]
Hi @egorovpavel,
Sorry for the late response.
I have tested the workaround and noticed the improvement. It looks that the printing capability works ok regardless of HTML representation of the source document.
The customer has been informed about the progress.
Best Regards.
