### ISSUE TITLE
Customizing content in the toolbar

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#59]
I noticed that if we need to change the content such as tooltips or logo text in the toolbar we can do it by updating _template_ of _ViewerAppComponent_ in `client\node_modules\@groupdocs.examples.angular\viewer\fesm2015\groupdocs.examples.angular-viewer.js` file and the changes are applied. However, there are multiple copies of this file in different subfolders of `viewer` folder (see [this](https://i.imgur.com/m0Ft79p.png)). Is it the correct way to just update `fesm2015\groupdocs.examples.angular-viewer.js` file and leave the others?

**Comment by egorovpavel** [comment]
Hi, @usmanazizgroupdocs 
Files in `node_modules` folder must not be changed as it's packages folder which means that you will lose your changes once a new or updated package is installed. 

Instead, we recommend extending Viewer app component as it explained [here](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/issues/40#issuecomment-523447609) and perform UI or any other changes in your [custom component](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/tree/custom-viewer-example/client/apps/viewer/src/app/custom-viewer) files. 

[Here](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/pull/41/files) is a complete example of how you can customize UI

Let me know if this works for you.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Thanks for sharing the guidelines.
