### ISSUE TITLE
JS error when running the application in IE 11

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#6]
This issue was originally raised via forum topic: [https://forum.groupdocs.com/t/ie-11-issue/6631/3](https://forum.groupdocs.com/t/ie-11-issue/6631/3)

The following JS error occurs when running the application in IE11 + Windows 10. 
Error details: ![js error](https://user-images.githubusercontent.com/16013722/46802971-650e3680-cd78-11e8-95f5-ddf1b5870bdd.png)

**Comment by shriharikale** [comment]
We have resolved IE 11 issues, resolutions are as below -

removed default parameter value (+ checked undefined and assigned value)
Added CDN ES6 JS libraries to support “promise” function
Function arrow (=>) pointers are removed with function.
Now its working fine. Please confirm resolution are correct and fine for front end application features

**Comment by bobkovalex** [comment]
@shriharikale 

Thank you for sharing this.

We will investigate your solution and then share our findings.
Please stay tuned.
