### ISSUE TITLE
Setting defaultDocument in configuration.yml is not working

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#60]
This issue is raised via forum topic: [https://forum.groupdocs.com/t/load-default-document/7601/5](https://forum.groupdocs.com/t/load-default-document/7601/5)

Setting **defaultDocument** property in _configuration.yml_ doesn't affect and the document doesn't load on the application's startup.

**Comment by kegor** [comment]
Hi @usmanazizgroupdocs, it's under investigation.

**Comment by kegor** [comment]
@usmanazizgroupdocs, the problem is identified and a code-fix will be added.

**Comment by kegor** [comment]
Hi @usmanazizgroupdocs, the fix will be shipped in the next release of https://github.com/groupdocs-total/GroupDocs.Total-Angular.

**Comment by kegor** [comment]
Hi @usmanazizgroupdocs, this issue has been fixed, please try latest release.
