### ISSUE TITLE
The command "..\node\win\node.exe ..\npm\bin\npm-cli.js install" exited with code 1.

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#61]
While building the latest release, I got the following error:
`The command "..\..\packages\Node-Kit.11.1.0.1\node\win\node.exe ..\..\packages\Node-Kit.11.1.0.1\npm\bin\npm-cli.js install" exited with code 1.`

**Environment:**
- VS 2015
- Windows 10 x64

![Error](https://user-images.githubusercontent.com/16013722/67087229-eb472f00-f1bb-11e9-9523-8ff8ecceea66.png)

**Comment by kegor** [comment]
Hi @usmanazizgroupdocs, could you please try to make `Clean->Rebuild` on a newly cloned repository in VS?

**Comment by usmanazizgroupdocs** [comment]
@kegor , I have tried cleaning and rebuilding the solution in VS but the error persists.

**Comment by kegor** [comment]
Hi @usmanazizgroupdocs, I was unable to reproduce this issue on my VS_2019/Win10_64 with a fresh clone of the repository, could you try steps from a similar issue [here](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms/issues/25#issuecomment-536059101)?

Let me know if it helps.

**Comment by usmanazizgroupdocs** [comment]
@kegor I referred to your provided steps and got it fixed by doing the following:

1. Reinstall Node
2. Delete node_modules folder
3. Run `npm cache clean --force`
4. Remove `npm `and `npm-cache` folders from `C:\Users\{username}\AppData\Roaming`
5. Run `npm install -g @angular/cli@latest` and `npm i`
6. Build the solution in Visual Studio

Thanks
